name: 04-using-actions.yaml
on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'

            - name: Install Dependencies
              run: npm ci
              working-directory: 04-using-actions/react-app

            - name: Run Unit Tests
              run: npm run test
              working-directory: 04-using-actions/react-app