on:
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Message
              run: echo "Running whenever a PR is closed"