name: 08 - Using Variables
on:
    # push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: "I am a workflow variable"
    OVERWRITTEN: "I will be overwritten"

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job variable"
            OVERWRITTEN: "I will be overwritten at job level"
        steps:
        - name: "Print env variables"
          env:
              STEP_VAR: "I am a step variable"
              OVERWRITTEN: "I will be overwritten at step level"
          run: |
            echo "Step env var: ${{ env.STEP_VAR }}"
            echo "Job env var: ${{ env.JOB_VAR }}"
            echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
            echo "Overwritten: ${{ env.OVERWRITTEN }}"
        - name: Overwrite job variable
          env:
            OVERWRITTEN: 'I have been overwritten at the step level'
          run: |
            echo "Step env var: ${{ env.OVERWRITTEN }}"